apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: teste
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    nodePort: 30001
  selector:
    app: nginx
  type: NodePort
